cabal-version:   3.14
name:            T325a
version:         0.1.0.0
license:         NONE
author:          Andrea Vezzosi
maintainer:      andrea@well-typed.com
build-type:      Simple
extra-doc-files: CHANGELOG.md

common warnings
    ghc-options: -Wall

executable T325
    import:           warnings
    main-is:          T325a.hs
    build-depends:    base
    hs-source-dirs:   .
    default-language: GHC2024
