# Warnings currently triggered by your code
- ignore: {name: "Eta reduce"} # 8 hints
- ignore: {name: "Evaluate"} # 4 hints
- ignore: {name: "Fuse mapM/map"} # 1 hint
- ignore: {name: "Move brackets to avoid $"} # 2 hints
- ignore: {name: "Redundant $"} # 4 hints
- ignore: {name: "Redundant <$>"} # 1 hint
- ignore: {name: "Redundant bracket"} # 23 hints
- ignore: {name: "Redundant lambda"} # 2 hints
- ignore: {name: "Redundant return"} # 3 hints
- ignore: {name: "Unused LANGUAGE pragma"} # 33 hints
- ignore: {name: "Use $>"} # 1 hint
- ignore: {name: "Use <$>"} # 4 hints
- ignore: {name: "Use camelCase"} # 4 hints
- ignore: {name: "Use elemIndex"} # 1 hint
- ignore: {name: "Use exitSuccess"} # 2 hints
- ignore: {name: "Use fewer LANGUAGE pragmas"} # 5 hints
- ignore: {name: "Use fewer imports"} # 1 hint
- ignore: {name: "Use handle"} # 1 hint
- ignore: {name: "Use list comprehension"} # 1 hint
- ignore: {name: "Use mapMaybe"} # 2 hints
- ignore: {name: "Use maybeToList"} # 1 hint
- ignore: {name: "Use newtype instead of data"} # 10 hints
- ignore: {name: "Use null"} # 1 hint
- ignore: {name: "Use optional"} # 1 hint
- ignore: {name: "Use or"} # 1 hint
- ignore: {name: "Use print"} # 5 hints
- ignore: {name: "Use record patterns"} # 1 hint
- ignore: {name: "Use uncurry"} # 2 hints
- ignore: {name: "Use unless"} # 2 hints
