name: action-deb11
description: Container for deb11
inputs:
  stage:
    description: which stage to build
    required: true
  version:
    description: which GHC version to build
    required: false
runs:
  using: docker
  image: debian:11
  entrypoint: .github/scripts/entrypoint.sh
  env:
    STAGE: ${{ inputs.stage }}
    GHC_VERSION: ${{ inputs.version }}
    INSTALL: apt-get -o Acquire::Check-Valid-Until=false update && apt-get install -y
    TOOLS: libnuma-dev zlib1g-dev libgmp-dev libgmp10 libssl-dev liblzma-dev libbz2-dev
      git wget lsb-release software-properties-common gnupg2 apt-transport-https gcc
      autoconf automake build-essential curl gzip libffi-dev libncurses-dev libncurses5
      libtinfo5 patchelf
