name: action-deb13
description: Container for deb13
inputs:
  stage:
    description: which stage to build
    required: true
  version:
    description: which GHC version to build
    required: false
runs:
  using: docker
  image: debian:13
  entrypoint: .github/scripts/entrypoint.sh
  env:
    STAGE: ${{ inputs.stage }}
    GHC_VERSION: ${{ inputs.version }}
    PKG_INSTALL_CMD: apt-get update && apt-get install -y
    PKG_TOOLS: libnuma-dev zlib1g-dev libgmp-dev libgmp10 libssl-dev liblzma-dev libbz2-dev
      git wget lsb-release gnupg2 apt-transport-https gcc autoconf automake build-essential
      curl gzip libffi-dev libncurses-dev patchelf
